{% set name = "cmarkgfm" %}
{% set version = "2022.10.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 93d9ac7716ea901ca0bfd18ae3b68f1f6bf51de0830c3f233ef734fcd52a0799

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cffi 1.15
    - python
    - pip
    - setuptools
    - wheel
    - {{ pin_compatible('m2w64-gcc-libs', max_pin='5.3.0') }}   # [win and py27]

  run:
    - cffi 1.15.0
    - python

test:
  requires: 
    - pip
  imports:
    - cmarkgfm
  commands:
    - pip check

about:
  home: https://github.com/jonparrott/cmarkgfm
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/jonparrott/cmarkgfm
  doc_url: https://pypi.org/project/cmarkgfm/
  description: Minimalist Python bindings to GitHub’s fork of cmark.
  documentation: https://pypi.org/project/cmarkgfm/
  summary: Minimalist Python bindings to GitHub’s fork of cmark.

extra:
  recipe-maintainers:
    - jjhelmus