{% set name = "cmarkgfm" %}
{% set version = "2024.11.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5dd01cf61975a8a57213cdef5ed870e936032f13fe93d60ddf659ffb9cf73c6a 

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv --ignore-installed

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cffi >=1.15.1
    - python
    - pip
    - setuptools
    - wheel

  run:
    - cffi >=1.15.1
    - python

test:
  requires: 
    - pip
  imports:
    - cmarkgfm
  commands:
    - pip check

about:
  home: https://github.com/theacodes/cmarkgfm
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/theacodes/cmarkgfm
  doc_url: https://pypi.org/project/cmarkgfm/
  description: Minimalist Python bindings to GitHub’s fork of cmark.
  documentation: https://pypi.org/project/cmarkgfm/
  summary: Minimalist Python bindings to GitHub’s fork of cmark.

extra:
  recipe-maintainers:
    - jjhelmus
