{% set name = "cmarkgfm" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fe859b0e98d222b4b458022007daac2757e970f0671d45e55d01931c1b4bb3cb

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv "

requirements:
  build:
    - pip
    - {{ compiler('c') }}  # [not (win and py27)]
  host:
    - cffi =>1.15.0
    - python
    - pip
    - wheel
    - libpython 2.1       # [win and py27]
    - {{ pin_compatible('m2w64-gcc-libs', max_pin='5.3.0') }}   # [win and py27]

  run:
    - cffi =>1.15.0
    - python
    - m2w64-gcc-libs   # [win and py27]

test:
  skip: True  # [osx]
  requires: 
    - pip
  imports:
    - cmarkgfm
  commands:
    - pip check

about:
  home: https://github.com/jonparrott/cmarkgfm
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/jonparrott/cmarkgfm
  doc_url: https://pypi.org/project/cmarkgfm/
  description: Minimalist Python bindings to GitHub’s fork of cmark.
  documentation: https://pypi.org/project/cmarkgfm/
  summary: Minimalist Python bindings to GitHub’s fork of cmark.

extra:
  recipe-maintainers:
    - jjhelmus