travis:
  secure:
    BINSTAR_TOKEN: CgCm3JLu4Rj38pKgkjJxNH1RuAwY8VKtGJQ4sp2yY1dKkDwH0oVSG4tvVc3ksQHidTH2m9PAGzdAbbdZdoAVfy4/k/gZFmBL88IJAD/yXZDP/Sf7Bds2XZ332thvlJQX3M8V4K/3ySSh93KxCFXGBgJKXVLjyZRCZ0qUyiXcxXPK7ry1tKrubPnz5dIHLuKBap3Yq0SH+g604nTM9niWqnOwjmOjnI7t/6/upqcezezcyrBpPPYFw9XTstQsKDv7n1koITeTE3cbHxAFvR9QFu4xF8GHgdQdRj3NiCZj+E7KxegT/GG5xegE+N7hNVVeeg/bRUUcUqZaUWfadMXjCc3pCrVwmVOTbOO6ycteRljJmI16IWGT78QN6sCTLl8T3IwdOVrzOpHOt5nfKvovnxpX1obm83iOr82fP4p8WVtlnDw8aMfC7DRkG/ItSuoxMkMdKF6t5ma62ZapM+ZCUejDA81S+kUcpCsdkqNRrccmrCpRpXHui2zYFr+vejpNGPX2z26OdWRvQg4OWuhuvdWcIoqvJhZs9Ug8+R3KTpd5Zb/Svxy72QsDUTPXgluSJCkqiNvf+vOiHHZDckaue0Io8bbJN9+3STKwG3FN201Kh6in8DhdDXmwLi8b7fFczKnxHeTnAwfVCewuZNPTN7E2DdTcwpNxgIrLMZuRW2U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
